---
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aweeraman/spring-microservices
          search-paths:
            - 'spring-config/*'
server:
  port: 8888